#!/usr/bin/env python3
"""
Power: OpenInfraMap / OSM Overpass agent (client-ready)

What it returns (dict):
- nearest_substation_name: keep original if present; otherwise autogenerated (voltage-based or ID)
- latin_name: simple transliteration (unidecode) or None
- substation_voltages_kV: list of numbers (kV)
- substation_distance_km: float (straight-line)
- nearest_lines: list (up to 3) of {id, name, voltage_kV (list), circuit_count (int|null), distance_km}
- last_updated: date string YYYY-MM-DD or "Unknown"

Search:
- tries 50 km first, if none found expands to 100 km
- uses bbox search for speed
- requires lines to have a voltage tag per client instruction
"""
import requests
import math
import re
from datetime import datetime
from typing import List, Dict, Any, Optional

OVERPASS_URLS = [
    "https://overpass-api.de/api/interpreter",
    "https://overpass.openstreetmap.ru/api/interpreter",
    "https://overpass.kumi.systems/api/interpreter"
]


def pick_overpass_server(timeout: float = 2.0) -> str:
    for url in OVERPASS_URLS:
        try:
            status = requests.get(url.replace("/interpreter", "/status"), timeout=timeout)
            if status.status_code == 200:
                return url
        except Exception:
            continue
    return OVERPASS_URLS[0]


# ---- Utilities ----
def haversine(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    R = 6371.0
    phi1 = math.radians(lat1)
    phi2 = math.radians(lat2)
    dphi = phi2 - phi1
    dlambda = math.radians(lon2 - lon1)
    a = math.sin(dphi / 2.0) ** 2 + math.cos(phi1) * math.cos(phi2) * math.sin(dlambda / 2.0) ** 2
    return 2 * R * math.asin(math.sqrt(a))


def bbox(lat: float, lon: float, km: float):
    dlat = km / 110.574
    dlon = km / (111.320 * math.cos(math.radians(lat)) + 1e-12)
    return lat - dlat, lon - dlon, lat + dlat, lon + dlon


def parse_voltage_to_kv(value) -> List[float]:
    """
    Parse voltage string/number and return list of kV values (floats), cleaned.
    Handles:
      - "110;380 kV", "110000;380000", "400000", "400"
      - separators: ';', ',', '/', ' '
    """
    if value is None:
        return []
    s = str(value)
    # remove common unit tokens to simplify parsing
    s = s.replace("kV", "").replace("KV", "").replace("kv", "")
    # split on separators
    tokens = re.split(r"[;,/|\s]+", s)
    kvs: List[float] = []
    for tok in tokens:
        tok = tok.strip()
        if not tok:
            continue
        # extract number
        m = re.search(r"[-+]?\d+(\.\d+)?", tok.replace(",", ""))
        if not m:
            continue
        num = float(m.group(0))
        # heuristic: values > 1000 likely volts -> convert to kV
        if num > 1000:
            num = num / 1000.0
        # round to reasonable precision and dedupe
        num = round(num, 3)
        if not any(abs(num - existing) < 1e-6 for existing in kvs):
            kvs.append(num)
    # sort descending (useful for display like 380/132)
    kvs.sort(reverse=True)
    return kvs


def parse_circuits(val) -> Optional[int]:
    if val is None:
        return None
    s = str(val)
    m = re.search(r"\d+", s)
    return int(m.group(0)) if m else None


def latinize(name: Optional[str]) -> Optional[str]:
    if not name:
        return None
    try:
        from unidecode import unidecode
        out = unidecode(name)
        return out if out.strip() else None
    except Exception:
        # if name is ASCII already, return it, else None
        if all(ord(c) < 128 for c in name):
            return name
        return None


# ---- Overpass query builder (fast bbox) ----
def build_query(lat: float, lon: float, radius_km: float) -> str:
    s, w, n, e = bbox(lat, lon, radius_km)
    # Query substations (node/way/relation) and lines/cables where voltage exists (client requested)
    q = f"""
[out:json][timeout:30][maxsize:200000000];
(
  node["power"="substation"]({s},{w},{n},{e});
  way["power"="substation"]({s},{w},{n},{e});
  relation["power"="substation"]({s},{w},{n},{e});

  node["power"~"line|cable"]["voltage"]({s},{w},{n},{e});
  way["power"~"line|cable"]["voltage"]({s},{w},{n},{e});
  relation["power"~"line|cable"]["voltage"]({s},{w},{n},{e});
);
out center tags meta;
"""
    return q


# ---- Auto-name substations when original name missing ----
def generate_substation_name(el: Dict[str, Any], voltages_kv: List[float]) -> str:
    # prefer original name/ref if available and not 'Unnamed'
    tags = el.get("tags", {}) or {}
    name = tags.get("name") or tags.get("ref")
    if name and str(name).strip().lower() != "unnamed":
        return name

    # voltage-based name
    if voltages_kv:
        kv_str = "/".join(str(int(v)) if v.is_integer() else str(v) for v in voltages_kv)
        return f"{kv_str} kV Substation"

    # use osm id if available
    oid = el.get("id")
    if oid:
        return f"Substation #{oid}"

    return "Unnamed Substation"


# ---- Main function (client-ready) ----
def find_power_assets(lat: float, lon: float) -> Dict[str, Any]:
    server = pick_overpass_server()
    elements = []
    used_radius = None

    # try 50 km then 100 km
    for radius in (50, 100):
        q = build_query(lat, lon, radius)
        try:
            resp = requests.post(server, data={"data": q}, timeout=60)
            resp.raise_for_status()
            js = resp.json()
            elements = js.get("elements", []) or []
            used_radius = radius
        except Exception as e:
            # if a server fails, try next radius (or we could try another server)
            elements = []
            used_radius = None
        # if any substation found, break
        found_sub = any((el.get("tags") or {}).get("power") == "substation" for el in elements)
        if found_sub:
            break

    # prepare collections
    substations: List[Dict[str, Any]] = []
    lines: List[Dict[str, Any]] = []
    all_timestamps: List[str] = []

    for el in elements:
        tags = el.get("tags") or {}
        power_tag = (tags.get("power") or "").lower()

        # determine centroid coords (out center meta returns .center for ways/relations)
        if "center" in el and el["center"] and isinstance(el["center"], dict):
            el_lat = el["center"].get("lat")
            el_lon = el["center"].get("lon")
        else:
            el_lat = el.get("lat")
            el_lon = el.get("lon")

        if el_lat is None or el_lon is None:
            continue

        ts = el.get("timestamp")
        if ts:
            all_timestamps.append(ts)

        # substations
        if power_tag == "substation":
            volt_kv = parse_voltage_to_kv(tags.get("voltage"))
            dist_km = round(haversine(lat, lon, el_lat, el_lon), 2)
            substations.append({
                "osm_id": el.get("id"),
                "original_name": tags.get("name") if tags.get("name") else None,
                "ref": tags.get("ref"),
                "voltages_kv": volt_kv,
                "lat": el_lat,
                "lon": el_lon,
                "distance_km": dist_km,
                "timestamp": ts,
                "element": el  # keep for id/tag access for naming
            })

        # lines / cables (only if voltage tag present per client)
        elif power_tag in ("line", "cable"):
            if not tags.get("voltage"):
                continue
            v = parse_voltage_to_kv(tags.get("voltage"))
            if not v:
                continue
            # Filter: only transmission infrastructure (>= 69 kV)
            if max(v) < 69:
                continue
            dist_km = round(haversine(lat, lon, el_lat, el_lon), 2)
            lines.append({
                "osm_id": el.get("id"),
                "name": tags.get("name") or tags.get("ref") or f"Line {el.get('id')}",
                "voltages_kv": v,
                "circuit_count": parse_circuits(tags.get("circuits")),
                "lat": el_lat,
                "lon": el_lon,
                "distance_km": dist_km,
                "timestamp": ts
            })

    # If no substations found at all
    if not substations:
        return {
            "nearest_substation_name": None,
            "latin_name": None,
            "substation_voltages_kV": [],
            "substation_distance_km": None,
            "nearest_lines": [],
            "last_updated": "Unknown",
            "search_radius_km": used_radius
        }

    # choose nearest substation
    substations.sort(key=lambda x: x["distance_km"])
    nearest = substations[0]
    # generate name (keep original if present)
    final_name = generate_substation_name(nearest["element"], nearest["voltages_kv"])
    latin_name = latinize(final_name)

    # pick nearest 1-3 lines with voltage sorted by distance
    lines.sort(key=lambda x: x["distance_km"])
    nearest_lines = lines[:3]

    # determine freshest timestamp among nearest substation and nearest lines
    relevant_ts = []
    if nearest.get("timestamp"):
        relevant_ts.append(nearest["timestamp"])
    for ln in nearest_lines:
        if ln.get("timestamp"):
            relevant_ts.append(ln["timestamp"])
    # fallback to any element timestamp if none on nearest features
    if not relevant_ts and all_timestamps:
        relevant_ts = all_timestamps

    if relevant_ts:
        # ISO timestamps -> pick max and reduce to YYYY-MM-DD
        try:
            latest = max(relevant_ts)
            last_updated = latest[:10]
        except Exception:
            last_updated = "Unknown"
    else:
        last_updated = "Unknown"

    # Build final result structure
    # Extract substation timestamp
    substation_timestamp = nearest.get("timestamp")
    if substation_timestamp:
        substation_timestamp = substation_timestamp[:10]  # YYYY-MM-DD
    else:
        substation_timestamp = "Unknown"

    result = {
        "nearest_substation_name": final_name,
        "latin_name": latin_name,
        "substation_voltages_kV": nearest.get("voltages_kv", []),
        "voltage_source": "osm_tag" if nearest.get("voltages_kv") else "not_available_in_osm",
        "substation_distance_km": nearest.get("distance_km"),
        "substation_last_updated": substation_timestamp,
        "nearest_lines": [
            {
                "id": ln["osm_id"],
                "name": ln["name"],
                "voltage_kV": ln["voltages_kv"],
                "circuit_count": ln["circuit_count"],
                "distance_km": ln["distance_km"],
                "last_updated": ln["timestamp"][:10] if ln.get("timestamp") else "Unknown"
            } for ln in nearest_lines
        ],
        "last_updated": last_updated,
        "search_radius_km": used_radius
    }

    return result


# ---- Human-readable summary (client example style) ----
def format_human_summary(res: Dict[str, Any]) -> str:
    if not res or not res.get("nearest_substation_name"):
        return "Nearest substation: None found within search radius."

    sub_name = res["nearest_substation_name"]
    volts = res.get("substation_voltages_kV", [])
    volts_str = "/".join(str(int(v)) if float(v).is_integer() else str(v) for v in volts) if volts else "Unknown kV"
    dist = res.get("substation_distance_km", "?")
    lines = res.get("nearest_lines", [])
    lines_parts = []
    for ln in lines:
        vlist = ln.get("voltage_kV", [])
        vstr = "/".join(str(int(v)) if float(v).is_integer() else str(v) for v in vlist) if vlist else "Unknown"
        circuits = ln.get("circuit_count")
        circ_str = f"({circuits} circuits)" if circuits is not None else "(circuits unknown)"
        lines_parts.append(f"{vstr} at {ln['distance_km']} km {circ_str}")
    lines_text = ", ".join(lines_parts) if lines_parts else "none"
    last = res.get("last_updated", "Unknown")
    return f"Nearest substation: {sub_name} {volts_str} kV, distance {dist} km; lines nearby: {lines_text}; last updated {last}."


# ---- Command line test entry ----
if __name__ == "__main__":
    # replace with any lat/lon you want to test
    test_coords = [
        (25.2048, 55.2708),   # Dubai downtown
        (26.2173, 50.1973),   # Al Khobar sample
    ]
    for lat, lon in test_coords:
        print(f"\nQuerying {lat}, {lon} ...")
        out = find_power_assets(lat, lon)
        import json
        print(json.dumps(out, indent=2, ensure_ascii=False))
        print("\nHuman summary:")
        print(format_human_summary(out))
